import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const productsData = [
  {
    "name": "Durafllor New Way  Nórdica",
    "slug": "durafllor-new-way-nordica",
    "category": "Laminado",
    "tone": "Claros",
    "imageUrl": "/images/produtos/durafllor-new-way-nordica.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafllor New Way  Nórdica é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor Link Córdoba",
    "slug": "durafloor-link-cordoba",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-link-cordoba.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor Link Córdoba é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor Nature Freijó Puro",
    "slug": "durafloor-nature-freijo-puro",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-nature-freijo-puro.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor Nature Freijó Puro é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor New Way - Amêndoa Curaçao",
    "slug": "durafloor-new-way-amendoa-curacao",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-new-way-amendoa-curacao.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor New Way - Amêndoa Curaçao é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor New Way Itapuã",
    "slug": "durafloor-new-way-itapua",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-new-way-itapua.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor New Way Itapuã é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor New Way Milão",
    "slug": "durafloor-new-way-milao",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-new-way-milao.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor New Way Milão é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Durafloor Studio Carvalho Malta",
    "slug": "durafloor-studio-carvalho-malta",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/durafloor-studio-carvalho-malta.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Durafloor Studio Carvalho Malta é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Eucafloor Grand Elegance Concreto",
    "slug": "eucafloor-grand-elegance-concreto",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/eucafloor-grand-elegance-concreto.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor Grand Elegance Concreto é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Eucafloor New Evidênce - Carvalho Córdoba",
    "slug": "eucafloor-new-evidence-carvalho-cordoba",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/eucafloor-new-evidence-carvalho-cordoba.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor New Evidênce - Carvalho Córdoba é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Eucafloor New Evidênce Moka",
    "slug": "eucafloor-new-evidence-moka",
    "category": "Laminado",
    "tone": "Escuros",
    "imageUrl": "/images/produtos/eucafloor-new-evidence-moka.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor New Evidênce Moka é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Eucafloor Prime Click Carvalho New",
    "slug": "eucafloor-prime-click-carvalho-new",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/eucafloor-prime-click-carvalho-new.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor Prime Click Carvalho New é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Mata Atlântica Pitanga",
    "slug": "mata-atlantica-pitanga",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/mata-atlantica-pitanga.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Mata Atlântica Pitanga é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step  Premiere Essencial Oak",
    "slug": "quick-step-premiere-essencial-oak",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-premiere-essencial-oak.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step  Premiere Essencial Oak é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step - Eligna Wide 3786 Castanheiro Antigo Restaurado",
    "slug": "quick-step-eligna-wide-3786-castanheiro-antigo-restaurado",
    "category": "Laminado",
    "tone": "Escuros",
    "imageUrl": "/images/produtos/quick-step-eligna-wide-3786-castanheiro-antigo-restaurado.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step - Eligna Wide 3786 Castanheiro Antigo Restaurado é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step - Smart - Carvalho Natural Midnight",
    "slug": "quick-step-smart-carvalho-natural-midnight",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-smart-carvalho-natural-midnight.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step - Smart - Carvalho Natural Midnight é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step Eligna Wide Carvalho Natural Serrado",
    "slug": "quick-step-eligna-wide-carvalho-natural-serrado",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-eligna-wide-carvalho-natural-serrado.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step Eligna Wide Carvalho Natural Serrado é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step Premiere Qpr 034 Carvalho Sacramento",
    "slug": "quick-step-premiere-qpr-034-carvalho-sacramento",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-premiere-qpr-034-carvalho-sacramento.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step Premiere Qpr 034 Carvalho Sacramento é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick Step Vision Cumarú Tefé",
    "slug": "quick-step-vision-cumaru-tefe",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-vision-cumaru-tefe.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick Step Vision Cumarú Tefé é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick-step Eligna Wide 3684 Castanheiro Natural Restaurado",
    "slug": "quick-step-eligna-wide-3684-castanheiro-natural-restaurado",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/quick-step-eligna-wide-3684-castanheiro-natural-restaurado.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick-step Eligna Wide 3684 Castanheiro Natural Restaurado é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Quick-step Smart Carvalho Vanilla",
    "slug": "quick-step-smart-carvalho-vanilla",
    "category": "Laminado",
    "tone": "Claros",
    "imageUrl": "/images/produtos/quick-step-smart-carvalho-vanilla.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Quick-step Smart Carvalho Vanilla é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Mata Atlântica Garça",
    "slug": "mata-atlantica-garca",
    "category": "Vinílico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/mata-atlantica-garca.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Mata Atlântica Garça é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Ecomex Eco Hard Servilha 125",
    "slug": "ecomex-eco-hard-servilha-125",
    "category": "Vinílico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/ecomex-eco-hard-servilha-125.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Ecomex Eco Hard Servilha 125 é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Ecomex Eco Home Nice",
    "slug": "ecomex-eco-home-nice",
    "category": "Vinílico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/ecomex-eco-home-nice.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Ecomex Eco Home Nice é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Elementar Flôr De Anis",
    "slug": "finottato-elementar-flor-de-anis",
    "category": "Vinílico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-elementar-flor-de-anis.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Elementar Flôr De Anis é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Personalittè Lorena",
    "slug": "finottato-personalitte-lorena",
    "category": "Vinílico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-personalitte-lorena.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Personalittè Lorena é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Prime Click Castanho Terracota",
    "slug": "prime-click-castanho-terracota-8",
    "category": "Laminado",
    "tone": "Tons Escuros",
    "imageUrl": "/images/prime-click-castanho-terracota.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Prime Click Castanho Terracota oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Click Kalahari",
    "slug": "piso-laminado-eucafloor-prime-click-kalahari-9",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-kalahari.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Click Kalahari oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado clicado Durafloor Nature Nagoya",
    "slug": "piso-laminado-clicado-durafloor-nature-nagoya-10",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-clicado-durafloor-nature-nagoya.webp",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado clicado Durafloor Nature Nagoya oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso vinílico Durafloor Urban Taos",
    "slug": "piso-vinilico-durafloor-urban-taos-11",
    "category": "Vinilico",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-taos-urban-durafloor.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Resistente à Água\"]",
    "thickness": "5mm",
    "resistance": "0.30mm (Capa)",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso vinílico Durafloor Urban Taos é a solução inteligente para quem busca praticidade sem abrir mão da elegância. 100% resistente à água, é ideal para todos os ambientes internos. Este padrão confere um visual contemporâneo, somado a um excelente conforto acústico e térmico.\"}"
  },
  {
    "name": "Piso Vinílico Durafloor City Petra",
    "slug": "piso-vinilico-durafloor-city-petra-12",
    "category": "Vinilico",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-durafloor-petra-city.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Resistente à Água\"]",
    "thickness": "5mm",
    "resistance": "0.30mm (Capa)",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso vinílico Durafloor City Petra é a solução inteligente para quem busca praticidade sem abrir mão da elegância. 100% resistente à água, é ideal para todos os ambientes internos. Este padrão confere um visual contemporâneo, somado a um excelente conforto acústico e térmico.\"}"
  },
  {
    "name": "Piso Laminado Unique Ultra Durafloor Toledo",
    "slug": "piso-laminado-unique-ultra-durafloor-toledo-13",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-unique-ultra-durafloor-toledo.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Unique Ultra Durafloor Toledo oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Cappuccino",
    "slug": "piso-laminado-eucafloor-prime-cappuccino-15",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-cappuccino.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Cappuccino oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor prime Noce Oro",
    "slug": "piso-laminado-eucafloor-prime-noce-oro-16",
    "category": "Laminado",
    "tone": "Tons Escuros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-noce-oro.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor prime Noce Oro oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor PRIME Carvalho",
    "slug": "piso-laminado-eucafloor-prime-carvalho-17",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-carvalho.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor PRIME Carvalho oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Carvalho Maiorca",
    "slug": "piso-laminado-eucafloor-prime-carvalho-maiorca-18",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-carvalho-maiorca.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Carvalho Maiorca oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Eucafloor New Evidênce Veneto",
    "slug": "eucafloor-new-evidence-veneto",
    "category": "Laminado",
    "tone": "Claros",
    "imageUrl": "/images/produtos/eucafloor-new-evidence-veneto.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor New Evidênce Veneto é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Imponente Caravela",
    "slug": "finottato-imponente-caravela",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-imponente-caravela.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Imponente Caravela é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Imponente Chocolate Suíço",
    "slug": "finottato-imponente-chocolate-suico",
    "category": "Vinilico",
    "tone": "Escuros",
    "imageUrl": "/images/produtos/finottato-imponente-chocolate-suico.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Imponente Chocolate Suíço é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Imponente Cosmos",
    "slug": "finottato-imponente-cosmos",
    "category": "Vinilico",
    "tone": "Escuros",
    "imageUrl": "/images/produtos/finottato-imponente-cosmos.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Imponente Cosmos é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Imponente Juba De Leão",
    "slug": "finottato-imponente-juba-de-leao",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-imponente-juba-de-leao.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Imponente Juba De Leão é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Imponente Rio Nilo",
    "slug": "finottato-imponente-rio-nilo",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-imponente-rio-nilo.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Imponente Rio Nilo é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Maximum Dijon",
    "slug": "finottato-maximum-dijon",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-maximum-dijon.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Maximum Dijon é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Maximum Lyon",
    "slug": "finottato-maximum-lyon",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-maximum-lyon.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Maximum Lyon é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Maximum Mônaco",
    "slug": "finottato-maximum-monaco",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-maximum-monaco.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Maximum Mônaco é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Maximum Nice",
    "slug": "finottato-maximum-nice",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-maximum-nice.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Maximum Nice é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Nativa - Doce De Caju",
    "slug": "finottato-nativa-doce-de-caju",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-nativa-doce-de-caju.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Nativa - Doce De Caju é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Nativa Algodão Egípcio",
    "slug": "finottato-nativa-algodao-egipcio",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-nativa-algodao-egipcio.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Nativa Algodão Egípcio é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Nativa Areia Do Sertão",
    "slug": "finottato-nativa-areia-do-sertao",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-nativa-areia-do-sertao.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Nativa Areia Do Sertão é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Nativa Ouro Branco",
    "slug": "finottato-nativa-ouro-branco",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-nativa-ouro-branco.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Nativa Ouro Branco é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Personnalite Turim",
    "slug": "finottato-personnalite-turim",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-personnalite-turim.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Personnalite Turim é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Personnalité Bolonha",
    "slug": "finottato-personnalite-bolonha",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-personnalite-bolonha.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Personnalité Bolonha é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Personnalité Milano",
    "slug": "finottato-personnalite-milano",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-personnalite-milano.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Personnalité Milano é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Personnalité Venezia",
    "slug": "finottato-personnalite-venezia",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-personnalite-venezia.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Personnalité Venezia é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Quadratta Cimento Queimado",
    "slug": "finottato-quadratta-cimento-queimado",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-quadratta-cimento-queimado.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Quadratta Cimento Queimado é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Quadratta Cinza Nevoeiro",
    "slug": "finottato-quadratta-cinza-nevoeiro",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-quadratta-cinza-nevoeiro.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Quadratta Cinza Nevoeiro é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Versatile Catania",
    "slug": "finottato-versatile-catania",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-versatile-catania.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Versatile Catania é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Versatile Molise",
    "slug": "finottato-versatile-molise",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-versatile-molise.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Versatile Molise é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Versatile Sardenha",
    "slug": "finottato-versatile-sardenha",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-versatile-sardenha.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Versatile Sardenha é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Versatile Toscana",
    "slug": "finottato-versatile-toscana",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-versatile-toscana.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Versatile Toscana é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Vital Canela",
    "slug": "finottato-vital-canela",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-vital-canela.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Vital Canela é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Vital Capim Dourado",
    "slug": "finottato-vital-capim-dourado",
    "category": "Vinilico",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/produtos/finottato-vital-capim-dourado.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Vital Capim Dourado é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Vital Luz Do Dia",
    "slug": "finottato-vital-luz-do-dia",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-vital-luz-do-dia.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Vital Luz Do Dia é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Vital Nevoeiro",
    "slug": "finottato-vital-nevoeiro",
    "category": "Vinilico",
    "tone": "Claros",
    "imageUrl": "/images/produtos/finottato-vital-nevoeiro.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Vital Nevoeiro é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Finottato Vital Terra Arada",
    "slug": "finottato-vital-terra-arada",
    "category": "Vinilico",
    "tone": "Escuros",
    "imageUrl": "/images/produtos/finottato-vital-terra-arada.jpeg",
    "benefits": null,
    "thickness": null,
    "resistance": null,
    "warranty": null,
    "techSpecsMisc": "{\"Descrição\":\"O Piso Vinílico Finottato Vital Terra Arada é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade, combinando perfeitamente com projetos contemporâneos e clássicos.\"}"
  },
  {
    "name": "Piso Laminado Gran Elegance Belmonte",
    "slug": "gran-elegance-belmonte-4",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/gran-elegance-belmonte.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Gran Elegance Belmonte oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Quick-Step Vision Carvalho Vitoriano",
    "slug": "piso-laminado-quick-step-vision-carvalho-vitoriano-1",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-quick-step-vision-carvalho-vitoriano.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Quick-Step Vision Carvalho Vitoriano oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Fresno Decape New",
    "slug": "piso-laminado-eucafloor-prime-fresno-decape-new-2",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-fresno-decape-new.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Fresno Decape New oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "piso laminado Eucafloor Prime CLICK - Carvalho Rústico",
    "slug": "piso-laminado-eucafloor-prime-click-carvalho-r-stico-3",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-carvalho-rustico.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado piso laminado Eucafloor Prime CLICK - Carvalho Rústico oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Max Elegance Claire Oak",
    "slug": "max-elegance-claire-oak-5",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/max-elegance-claire-oak.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Max Elegance Claire Oak oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "New Evidence Click Moka",
    "slug": "new-evidence-click-moka-6",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/new-evidence-click-moka.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado New Evidence Click Moka oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Square Mármore Imperador",
    "slug": "square-m-rmore-imperador-7",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/square-marmore-imperador.jpeg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Square Mármore Imperador oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Click Andorra New",
    "slug": "piso-laminado-eucafloor-prime-click-andorra-new-19",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-andorra-new.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Click Andorra New oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Quick Step Floorest PREMIERE Malta 1067",
    "slug": "piso-laminado-quick-step-floorest-premiere-malta-1067-20",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-quick-step-floorest-premiere-malta-1067.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Quick Step Floorest PREMIERE Malta 1067 oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Durafloor New Way Carvalho York",
    "slug": "piso-laminado-durafloor-new-way-carvalho-york-21",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-durafloor-new-way-carvalho-york.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Durafloor New Way Carvalho York oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Click - Decapê",
    "slug": "piso-laminado-eucafloor-prime-click-decap-22",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-decape.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Click - Decapê oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Click Carvalho Coimbra",
    "slug": "piso-laminado-eucafloor-prime-click-carvalho-coimbra-23",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-carvalho-coimbra.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Click Carvalho Coimbra oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Click Carvalho canela",
    "slug": "piso-laminado-eucafloor-prime-click-carvalho-canela-24",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-carvalho-canela.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Click Carvalho canela oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Click Italian Noce",
    "slug": "piso-laminado-eucafloor-prime-click-italian-noce-25",
    "category": "Laminado",
    "tone": "Tons Escuros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-italian-noce.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Click Italian Noce oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor prime Lâmina Amêndoa",
    "slug": "piso-laminado-eucafloor-prime-l-mina-am-ndoa-26",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-lamina-amendoa.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor prime Lâmina Amêndoa oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Click Nogueira Malaga",
    "slug": "piso-laminado-eucafloor-prime-click-nogueira-malaga-27",
    "category": "Laminado",
    "tone": "Tons Escuros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-nogueira-malaga.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Click Nogueira Malaga oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Click Nogueira Natural",
    "slug": "piso-laminado-eucafloor-prime-click-nogueira-natural-28",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-nogueira-natural.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Click Nogueira Natural oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Elmo Natural",
    "slug": "piso-laminado-eucafloor-prime-elmo-natural-29",
    "category": "Laminado",
    "tone": "Amadeirados Quentes",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-elmo-natural.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Elmo Natural oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso laminado Eucafloor Prime Valência",
    "slug": "piso-laminado-eucafloor-prime-val-ncia-30",
    "category": "Laminado",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-valencia.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso laminado Eucafloor Prime Valência oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso Laminado Eucafloor Prime Click Cacau Rodapé Cor Do Piso",
    "slug": "piso-laminado-eucafloor-prime-click-cacau-rodap-cor-do-piso-31",
    "category": "Laminado",
    "tone": "Tons Escuros",
    "imageUrl": "/images/piso-laminado-eucafloor-prime-click-cacau-rodape-cor-do-piso.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Conforto Térmico\"]",
    "thickness": "7mm",
    "resistance": "AC3",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso laminado Piso Laminado Eucafloor Prime Click Cacau Rodapé Cor Do Piso oferece o equilíbrio ideal entre durabilidade e sofisticação. Sua tecnologia avançada garante alta resistência a riscos e facilidade de limpeza, tornando-o perfeito para ambientes residenciais e comerciais de tráfego moderado. Transforme seu espaço com o conforto e a estética acolhedora da madeira.\"}"
  },
  {
    "name": "Piso vinílico tarkett Injoy Papoula",
    "slug": "piso-vin-lico-tarkett-injoy-papoula-36",
    "category": "Vinilico",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-vinilico-tarkett-injoy-papoula.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Resistente à Água\"]",
    "thickness": "5mm",
    "resistance": "0.30mm (Capa)",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso vinílico Piso vinílico tarkett Injoy Papoula é a solução inteligente para quem busca praticidade sem abrir mão da elegância. 100% resistente à água, é ideal para todos os ambientes internos. Este padrão confere um visual contemporâneo, somado a um excelente conforto acústico e térmico.\"}"
  },
  {
    "name": "Piso vinílico Finottato Imponente Chocolate Suíço",
    "slug": "piso-vin-lico-finottato-imponente-chocolate-su-o-39",
    "category": "Vinilico",
    "tone": "Tons Escuros",
    "imageUrl": "/images/piso-vinilico-finottato-imponente-chocolate-suico.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Resistente à Água\"]",
    "thickness": "5mm",
    "resistance": "0.30mm (Capa)",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso vinílico Piso vinílico Finottato Imponente Chocolate Suíço é a solução inteligente para quem busca praticidade sem abrir mão da elegância. 100% resistente à água, é ideal para todos os ambientes internos. Este padrão confere um visual contemporâneo, somado a um excelente conforto acústico e térmico.\"}"
  },
  {
    "name": "Piso vinílico Vinilforte (cinza) granada",
    "slug": "piso-vin-lico-vinilforte-cinza-granada-40",
    "category": "Vinilico",
    "tone": "Tons Claros",
    "imageUrl": "/images/piso-vinilico-vinilforte-cinza-granada.jpg",
    "benefits": "[\"Instalação rápida\",\"Acabamento impecável\",\"Resistente à Água\"]",
    "thickness": "5mm",
    "resistance": "0.30mm (Capa)",
    "warranty": "10 anos",
    "techSpecsMisc": "{\"Descrição\":\"O piso vinílico Piso vinílico Vinilforte (cinza) granada é a solução inteligente para quem busca praticidade sem abrir mão da elegância. 100% resistente à água, é ideal para todos os ambientes internos. Este padrão confere um visual contemporâneo, somado a um excelente conforto acústico e térmico.\"}"
  },
  {
    "name": "Eucafloor New Evidênce Veneto",
    "slug": "piso-laminado-eucafloor-new-evidence-veneto",
    "category": "Laminado",
    "tone": "Claros",
    "imageUrl": "/images/produtos/piso-laminado-eucafloor-new-evidence-veneto.jpeg",
    "techSpecsMisc": "{\"Descrição\":\"O Piso Laminado Eucafloor New Evidênce Veneto é a escolha perfeita para ambientes que buscam elegância, conforto termoacústico e alta durabilidade.\"}"
  }
];

  console.log('🌱 Semeando banco de dados com ' + productsData.length + ' produtos...')

  for (const data of productsData) {
    await prisma.product.upsert({
      where: { slug: data.slug },
      update: data,
      create: data,
    })
  }

  console.log('✅ Semeadura concluída com sucesso.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })